# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: UI Unit Tests

on:
  push:
    paths:
      - app/**
      - .github/**

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Generate Expo types
        run: pnpm exec expo customize tsconfig.json
        working-directory: ./app
      - name: Typecheck
        run: pnpm run typecheck
        working-directory: ./app
      - name: Lint
        run: pnpm run lint
        working-directory: ./app
      - name: Test
        run: pnpm test
        working-directory: ./app
